<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>de.in</groupId>
	<artifactId>dicomeditor</artifactId>
	<version>0.1.0</version>
	<name>DicomEditor</name>

	<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>DCM4CHE</id>
			<name>DCM4CHE</name>
			<url>https://www.dcm4che.org/maven2/</url>
		</repository>
		<repository>
			<id>github-utils</id>
			<url>https://maven.pkg.github.com/TiJaWo68/utils</url>
		</repository>
		<repository>
			<id>github-updraft</id>
			<url>https://maven.pkg.github.com/TiJaWo68/simpleupdraft4j</url>
		</repository>
	</repositories>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.target>21</maven.compiler.target>
		<maven.compiler.source>21</maven.compiler.source>
		<dcm4che.version>5.34.3</dcm4che.version>
		<dcm4che.version>5.34.2</dcm4che.version>
		<log4j2.version>2.25.4</log4j2.version>
		<slf4j.version>1.7.5</slf4j.version>
		<flatlaf.version>3.7.1</flatlaf.version>
		<utils.version>[2.0.0,3.0.0)</utils.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>de.in</groupId>
			<artifactId>utils</artifactId>
			<version>${utils.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.dcm4che.tool</groupId>
					<artifactId>dcm4che-tool-dcm2jpg</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.dcm4che</groupId>
					<artifactId>dcm4che-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.github.oshi</groupId>
					<artifactId>oshi-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jfree</groupId>
					<artifactId>jcommon</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che/dcm4che-core -->
		<dependency>
			<groupId>org.dcm4che</groupId>
			<artifactId>dcm4che-core</artifactId>
			<version>${dcm4che.version}</version>
		</dependency>
		<!-- Source: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core -->
		<dependency>
		    <groupId>org.apache.logging.log4j</groupId>
		    <artifactId>log4j-core</artifactId>
			<version>${log4j2.version}</version>
		</dependency>		
		<!-- https://mvnrepository.com/artifact/com.formdev/flatlaf -->
		<dependency>
			<groupId>com.formdev</groupId>
			<artifactId>flatlaf</artifactId>
			<version>${flatlaf.version}</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>de.in</groupId>
			<artifactId>simpleupdraft4j</artifactId>
			<version>[0.1.6,2.0.0)</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.15.0</version>
				<configuration>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<classpathPrefix>lib/</classpathPrefix>
							<mainClass>de.in.dicom.tools.DicomEditor</mainClass>
						</manifest>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.10.0</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/lib</outputDirectory>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>license-maven-plugin</artifactId>
				<version>2.7.1</version>
				<executions>
					<execution>
						<id>download-licenses</id>
						<goals>
							<goal>download-licenses</goal>
						</goals>
						<phase>generate-resources</phase>
						<configuration>
							<licensesOutputDirectory>${project.build.directory}/classes</licensesOutputDirectory>
							<licensesOutputFile>${project.build.directory}/classes/licenses.xml</licensesOutputFile>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>